// Node Initialization gRPC Service Definitions
// Extends steep.repl.v1 with initialization operations

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: internal/repl/grpc/proto/init.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InitService_StartInit_FullMethodName               = "/steep.repl.v1.InitService/StartInit"
	InitService_PrepareInit_FullMethodName             = "/steep.repl.v1.InitService/PrepareInit"
	InitService_CompleteInit_FullMethodName            = "/steep.repl.v1.InitService/CompleteInit"
	InitService_CancelInit_FullMethodName              = "/steep.repl.v1.InitService/CancelInit"
	InitService_GetProgress_FullMethodName             = "/steep.repl.v1.InitService/GetProgress"
	InitService_StreamProgress_FullMethodName          = "/steep.repl.v1.InitService/StreamProgress"
	InitService_StartReinit_FullMethodName             = "/steep.repl.v1.InitService/StartReinit"
	InitService_CompareSchemas_FullMethodName          = "/steep.repl.v1.InitService/CompareSchemas"
	InitService_GetSchemaFingerprints_FullMethodName   = "/steep.repl.v1.InitService/GetSchemaFingerprints"
	InitService_GetColumnDiff_FullMethodName           = "/steep.repl.v1.InitService/GetColumnDiff"
	InitService_CaptureFingerprints_FullMethodName     = "/steep.repl.v1.InitService/CaptureFingerprints"
	InitService_GenerateSnapshot_FullMethodName        = "/steep.repl.v1.InitService/GenerateSnapshot"
	InitService_ApplySnapshot_FullMethodName           = "/steep.repl.v1.InitService/ApplySnapshot"
	InitService_StartBidirectionalMerge_FullMethodName = "/steep.repl.v1.InitService/StartBidirectionalMerge"
)

// InitServiceClient is the client API for InitService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InitServiceClient interface {
	// Start automatic snapshot initialization
	StartInit(ctx context.Context, in *StartInitRequest, opts ...grpc.CallOption) (*StartInitResponse, error)
	// Prepare for manual initialization (creates slot, returns LSN)
	PrepareInit(ctx context.Context, in *PrepareInitRequest, opts ...grpc.CallOption) (*PrepareInitResponse, error)
	// Complete manual initialization
	CompleteInit(ctx context.Context, in *CompleteInitRequest, opts ...grpc.CallOption) (*CompleteInitResponse, error)
	// Cancel in-progress initialization
	CancelInit(ctx context.Context, in *CancelInitRequest, opts ...grpc.CallOption) (*CancelInitResponse, error)
	// Get current initialization progress
	GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error)
	// Stream real-time progress updates
	StreamProgress(ctx context.Context, in *StreamProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error)
	// Start reinitialization
	StartReinit(ctx context.Context, in *StartReinitRequest, opts ...grpc.CallOption) (*StartReinitResponse, error)
	// Compare schemas between nodes
	CompareSchemas(ctx context.Context, in *CompareSchemasRequest, opts ...grpc.CallOption) (*CompareSchemasResponse, error)
	// Get schema fingerprints from this node's database
	GetSchemaFingerprints(ctx context.Context, in *GetSchemaFingerprintsRequest, opts ...grpc.CallOption) (*GetSchemaFingerprintsResponse, error)
	// Get column-level differences for a specific table
	GetColumnDiff(ctx context.Context, in *GetColumnDiffRequest, opts ...grpc.CallOption) (*GetColumnDiffResponse, error)
	// Capture fingerprints for tables in the local database
	CaptureFingerprints(ctx context.Context, in *CaptureFingerprintsRequest, opts ...grpc.CallOption) (*CaptureFingerprintsResponse, error)
	// Generate snapshot (two-phase, phase 1)
	GenerateSnapshot(ctx context.Context, in *GenerateSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotProgress], error)
	// Apply snapshot (two-phase, phase 2)
	ApplySnapshot(ctx context.Context, in *ApplySnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotProgress], error)
	// Start bidirectional merge initialization
	StartBidirectionalMerge(ctx context.Context, in *StartBidirectionalMergeRequest, opts ...grpc.CallOption) (*StartBidirectionalMergeResponse, error)
}

type initServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInitServiceClient(cc grpc.ClientConnInterface) InitServiceClient {
	return &initServiceClient{cc}
}

func (c *initServiceClient) StartInit(ctx context.Context, in *StartInitRequest, opts ...grpc.CallOption) (*StartInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartInitResponse)
	err := c.cc.Invoke(ctx, InitService_StartInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) PrepareInit(ctx context.Context, in *PrepareInitRequest, opts ...grpc.CallOption) (*PrepareInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareInitResponse)
	err := c.cc.Invoke(ctx, InitService_PrepareInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) CompleteInit(ctx context.Context, in *CompleteInitRequest, opts ...grpc.CallOption) (*CompleteInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteInitResponse)
	err := c.cc.Invoke(ctx, InitService_CompleteInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) CancelInit(ctx context.Context, in *CancelInitRequest, opts ...grpc.CallOption) (*CancelInitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelInitResponse)
	err := c.cc.Invoke(ctx, InitService_CancelInit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) GetProgress(ctx context.Context, in *GetProgressRequest, opts ...grpc.CallOption) (*GetProgressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProgressResponse)
	err := c.cc.Invoke(ctx, InitService_GetProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) StreamProgress(ctx context.Context, in *StreamProgressRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ProgressUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InitService_ServiceDesc.Streams[0], InitService_StreamProgress_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamProgressRequest, ProgressUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InitService_StreamProgressClient = grpc.ServerStreamingClient[ProgressUpdate]

func (c *initServiceClient) StartReinit(ctx context.Context, in *StartReinitRequest, opts ...grpc.CallOption) (*StartReinitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartReinitResponse)
	err := c.cc.Invoke(ctx, InitService_StartReinit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) CompareSchemas(ctx context.Context, in *CompareSchemasRequest, opts ...grpc.CallOption) (*CompareSchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareSchemasResponse)
	err := c.cc.Invoke(ctx, InitService_CompareSchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) GetSchemaFingerprints(ctx context.Context, in *GetSchemaFingerprintsRequest, opts ...grpc.CallOption) (*GetSchemaFingerprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSchemaFingerprintsResponse)
	err := c.cc.Invoke(ctx, InitService_GetSchemaFingerprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) GetColumnDiff(ctx context.Context, in *GetColumnDiffRequest, opts ...grpc.CallOption) (*GetColumnDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetColumnDiffResponse)
	err := c.cc.Invoke(ctx, InitService_GetColumnDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) CaptureFingerprints(ctx context.Context, in *CaptureFingerprintsRequest, opts ...grpc.CallOption) (*CaptureFingerprintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureFingerprintsResponse)
	err := c.cc.Invoke(ctx, InitService_CaptureFingerprints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *initServiceClient) GenerateSnapshot(ctx context.Context, in *GenerateSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InitService_ServiceDesc.Streams[1], InitService_GenerateSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GenerateSnapshotRequest, SnapshotProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InitService_GenerateSnapshotClient = grpc.ServerStreamingClient[SnapshotProgress]

func (c *initServiceClient) ApplySnapshot(ctx context.Context, in *ApplySnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotProgress], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &InitService_ServiceDesc.Streams[2], InitService_ApplySnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ApplySnapshotRequest, SnapshotProgress]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InitService_ApplySnapshotClient = grpc.ServerStreamingClient[SnapshotProgress]

func (c *initServiceClient) StartBidirectionalMerge(ctx context.Context, in *StartBidirectionalMergeRequest, opts ...grpc.CallOption) (*StartBidirectionalMergeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartBidirectionalMergeResponse)
	err := c.cc.Invoke(ctx, InitService_StartBidirectionalMerge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InitServiceServer is the server API for InitService service.
// All implementations must embed UnimplementedInitServiceServer
// for forward compatibility.
type InitServiceServer interface {
	// Start automatic snapshot initialization
	StartInit(context.Context, *StartInitRequest) (*StartInitResponse, error)
	// Prepare for manual initialization (creates slot, returns LSN)
	PrepareInit(context.Context, *PrepareInitRequest) (*PrepareInitResponse, error)
	// Complete manual initialization
	CompleteInit(context.Context, *CompleteInitRequest) (*CompleteInitResponse, error)
	// Cancel in-progress initialization
	CancelInit(context.Context, *CancelInitRequest) (*CancelInitResponse, error)
	// Get current initialization progress
	GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error)
	// Stream real-time progress updates
	StreamProgress(*StreamProgressRequest, grpc.ServerStreamingServer[ProgressUpdate]) error
	// Start reinitialization
	StartReinit(context.Context, *StartReinitRequest) (*StartReinitResponse, error)
	// Compare schemas between nodes
	CompareSchemas(context.Context, *CompareSchemasRequest) (*CompareSchemasResponse, error)
	// Get schema fingerprints from this node's database
	GetSchemaFingerprints(context.Context, *GetSchemaFingerprintsRequest) (*GetSchemaFingerprintsResponse, error)
	// Get column-level differences for a specific table
	GetColumnDiff(context.Context, *GetColumnDiffRequest) (*GetColumnDiffResponse, error)
	// Capture fingerprints for tables in the local database
	CaptureFingerprints(context.Context, *CaptureFingerprintsRequest) (*CaptureFingerprintsResponse, error)
	// Generate snapshot (two-phase, phase 1)
	GenerateSnapshot(*GenerateSnapshotRequest, grpc.ServerStreamingServer[SnapshotProgress]) error
	// Apply snapshot (two-phase, phase 2)
	ApplySnapshot(*ApplySnapshotRequest, grpc.ServerStreamingServer[SnapshotProgress]) error
	// Start bidirectional merge initialization
	StartBidirectionalMerge(context.Context, *StartBidirectionalMergeRequest) (*StartBidirectionalMergeResponse, error)
	mustEmbedUnimplementedInitServiceServer()
}

// UnimplementedInitServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInitServiceServer struct{}

func (UnimplementedInitServiceServer) StartInit(context.Context, *StartInitRequest) (*StartInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInit not implemented")
}
func (UnimplementedInitServiceServer) PrepareInit(context.Context, *PrepareInitRequest) (*PrepareInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareInit not implemented")
}
func (UnimplementedInitServiceServer) CompleteInit(context.Context, *CompleteInitRequest) (*CompleteInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteInit not implemented")
}
func (UnimplementedInitServiceServer) CancelInit(context.Context, *CancelInitRequest) (*CancelInitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInit not implemented")
}
func (UnimplementedInitServiceServer) GetProgress(context.Context, *GetProgressRequest) (*GetProgressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgress not implemented")
}
func (UnimplementedInitServiceServer) StreamProgress(*StreamProgressRequest, grpc.ServerStreamingServer[ProgressUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamProgress not implemented")
}
func (UnimplementedInitServiceServer) StartReinit(context.Context, *StartReinitRequest) (*StartReinitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartReinit not implemented")
}
func (UnimplementedInitServiceServer) CompareSchemas(context.Context, *CompareSchemasRequest) (*CompareSchemasResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareSchemas not implemented")
}
func (UnimplementedInitServiceServer) GetSchemaFingerprints(context.Context, *GetSchemaFingerprintsRequest) (*GetSchemaFingerprintsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSchemaFingerprints not implemented")
}
func (UnimplementedInitServiceServer) GetColumnDiff(context.Context, *GetColumnDiffRequest) (*GetColumnDiffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetColumnDiff not implemented")
}
func (UnimplementedInitServiceServer) CaptureFingerprints(context.Context, *CaptureFingerprintsRequest) (*CaptureFingerprintsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CaptureFingerprints not implemented")
}
func (UnimplementedInitServiceServer) GenerateSnapshot(*GenerateSnapshotRequest, grpc.ServerStreamingServer[SnapshotProgress]) error {
	return status.Error(codes.Unimplemented, "method GenerateSnapshot not implemented")
}
func (UnimplementedInitServiceServer) ApplySnapshot(*ApplySnapshotRequest, grpc.ServerStreamingServer[SnapshotProgress]) error {
	return status.Error(codes.Unimplemented, "method ApplySnapshot not implemented")
}
func (UnimplementedInitServiceServer) StartBidirectionalMerge(context.Context, *StartBidirectionalMergeRequest) (*StartBidirectionalMergeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartBidirectionalMerge not implemented")
}
func (UnimplementedInitServiceServer) mustEmbedUnimplementedInitServiceServer() {}
func (UnimplementedInitServiceServer) testEmbeddedByValue()                     {}

// UnsafeInitServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InitServiceServer will
// result in compilation errors.
type UnsafeInitServiceServer interface {
	mustEmbedUnimplementedInitServiceServer()
}

func RegisterInitServiceServer(s grpc.ServiceRegistrar, srv InitServiceServer) {
	// If the following call panics, it indicates UnimplementedInitServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InitService_ServiceDesc, srv)
}

func _InitService_StartInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).StartInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_StartInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).StartInit(ctx, req.(*StartInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_PrepareInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).PrepareInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_PrepareInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).PrepareInit(ctx, req.(*PrepareInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_CompleteInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).CompleteInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_CompleteInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).CompleteInit(ctx, req.(*CompleteInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_CancelInit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).CancelInit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_CancelInit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).CancelInit(ctx, req.(*CancelInitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_GetProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).GetProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_GetProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).GetProgress(ctx, req.(*GetProgressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_StreamProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamProgressRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InitServiceServer).StreamProgress(m, &grpc.GenericServerStream[StreamProgressRequest, ProgressUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InitService_StreamProgressServer = grpc.ServerStreamingServer[ProgressUpdate]

func _InitService_StartReinit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartReinitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).StartReinit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_StartReinit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).StartReinit(ctx, req.(*StartReinitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_CompareSchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareSchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).CompareSchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_CompareSchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).CompareSchemas(ctx, req.(*CompareSchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_GetSchemaFingerprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSchemaFingerprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).GetSchemaFingerprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_GetSchemaFingerprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).GetSchemaFingerprints(ctx, req.(*GetSchemaFingerprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_GetColumnDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetColumnDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).GetColumnDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_GetColumnDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).GetColumnDiff(ctx, req.(*GetColumnDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_CaptureFingerprints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureFingerprintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).CaptureFingerprints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_CaptureFingerprints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).CaptureFingerprints(ctx, req.(*CaptureFingerprintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InitService_GenerateSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GenerateSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InitServiceServer).GenerateSnapshot(m, &grpc.GenericServerStream[GenerateSnapshotRequest, SnapshotProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InitService_GenerateSnapshotServer = grpc.ServerStreamingServer[SnapshotProgress]

func _InitService_ApplySnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ApplySnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(InitServiceServer).ApplySnapshot(m, &grpc.GenericServerStream[ApplySnapshotRequest, SnapshotProgress]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type InitService_ApplySnapshotServer = grpc.ServerStreamingServer[SnapshotProgress]

func _InitService_StartBidirectionalMerge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartBidirectionalMergeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InitServiceServer).StartBidirectionalMerge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InitService_StartBidirectionalMerge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InitServiceServer).StartBidirectionalMerge(ctx, req.(*StartBidirectionalMergeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InitService_ServiceDesc is the grpc.ServiceDesc for InitService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InitService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "steep.repl.v1.InitService",
	HandlerType: (*InitServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartInit",
			Handler:    _InitService_StartInit_Handler,
		},
		{
			MethodName: "PrepareInit",
			Handler:    _InitService_PrepareInit_Handler,
		},
		{
			MethodName: "CompleteInit",
			Handler:    _InitService_CompleteInit_Handler,
		},
		{
			MethodName: "CancelInit",
			Handler:    _InitService_CancelInit_Handler,
		},
		{
			MethodName: "GetProgress",
			Handler:    _InitService_GetProgress_Handler,
		},
		{
			MethodName: "StartReinit",
			Handler:    _InitService_StartReinit_Handler,
		},
		{
			MethodName: "CompareSchemas",
			Handler:    _InitService_CompareSchemas_Handler,
		},
		{
			MethodName: "GetSchemaFingerprints",
			Handler:    _InitService_GetSchemaFingerprints_Handler,
		},
		{
			MethodName: "GetColumnDiff",
			Handler:    _InitService_GetColumnDiff_Handler,
		},
		{
			MethodName: "CaptureFingerprints",
			Handler:    _InitService_CaptureFingerprints_Handler,
		},
		{
			MethodName: "StartBidirectionalMerge",
			Handler:    _InitService_StartBidirectionalMerge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamProgress",
			Handler:       _InitService_StreamProgress_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GenerateSnapshot",
			Handler:       _InitService_GenerateSnapshot_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ApplySnapshot",
			Handler:       _InitService_ApplySnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/repl/grpc/proto/init.proto",
}
