// steep_repl gRPC Service Definitions
// Node-to-node communication protocol for bidirectional replication coordination

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: internal/repl/grpc/proto/repl.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_repl_grpc_proto_repl_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_internal_repl_grpc_proto_repl_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: specific service to check (empty = overall health)
	Service       string `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

type HealthCheckResponse struct {
	state  protoimpl.MessageState            `protogen:"open.v1"`
	Status HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=steep.repl.v1.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	// Component health breakdown
	Components map[string]*ComponentHealth `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Node metadata
	NodeId        string                 `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,4,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	UptimeSince   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=uptime_since,json=uptimeSince,proto3" json:"uptime_since,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetComponents() map[string]*ComponentHealth {
	if x != nil {
		return x.Components
	}
	return nil
}

func (x *HealthCheckResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HealthCheckResponse) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetUptimeSince() *timestamppb.Timestamp {
	if x != nil {
		return x.UptimeSince
	}
	return nil
}

type ComponentHealth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`   // "connected", "disconnected", "error", etc.
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"` // Optional detail message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComponentHealth) Reset() {
	*x = ComponentHealth{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComponentHealth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComponentHealth) ProtoMessage() {}

func (x *ComponentHealth) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComponentHealth.ProtoReflect.Descriptor instead.
func (*ComponentHealth) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{2}
}

func (x *ComponentHealth) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *ComponentHealth) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ComponentHealth) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RegisterNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeRequest) Reset() {
	*x = RegisterNodeRequest{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeRequest) ProtoMessage() {}

func (x *RegisterNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterNodeRequest) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterNodeRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterNodeRequest) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *RegisterNodeRequest) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *RegisterNodeRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RegisterNodeRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type RegisterNodeResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error   string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	// Current cluster state
	Nodes         []*NodeInfo `protobuf:"bytes,3,rep,name=nodes,proto3" json:"nodes,omitempty"`
	CoordinatorId string      `protobuf:"bytes,4,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterNodeResponse) Reset() {
	*x = RegisterNodeResponse{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterNodeResponse) ProtoMessage() {}

func (x *RegisterNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterNodeResponse) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterNodeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterNodeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *RegisterNodeResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *RegisterNodeResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

type GetNodesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Optional: filter by status
	StatusFilter  []string `protobuf:"bytes,1,rep,name=status_filter,json=statusFilter,proto3" json:"status_filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesRequest) Reset() {
	*x = GetNodesRequest{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesRequest) ProtoMessage() {}

func (x *GetNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesRequest.ProtoReflect.Descriptor instead.
func (*GetNodesRequest) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{5}
}

func (x *GetNodesRequest) GetStatusFilter() []string {
	if x != nil {
		return x.StatusFilter
	}
	return nil
}

type GetNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*NodeInfo            `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	CoordinatorId string                 `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodesResponse) Reset() {
	*x = GetNodesResponse{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodesResponse) ProtoMessage() {}

func (x *GetNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodesResponse.ProtoReflect.Descriptor instead.
func (*GetNodesResponse) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{6}
}

func (x *GetNodesResponse) GetNodes() []*NodeInfo {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *GetNodesResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Host          string                 `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port          int32                  `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	IsCoordinator bool                   `protobuf:"varint,6,opt,name=is_coordinator,json=isCoordinator,proto3" json:"is_coordinator,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"` // "unknown", "healthy", "degraded", "unreachable", "offline"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{7}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeInfo) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NodeInfo) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NodeInfo) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *NodeInfo) GetIsCoordinator() bool {
	if x != nil {
		return x.IsCoordinator
	}
	return false
}

func (x *NodeInfo) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *NodeInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type HeartbeatRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Optional: include current node status
	NodeStatus    *NodeStatus `protobuf:"bytes,2,opt,name=node_status,json=nodeStatus,proto3" json:"node_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{8}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetNodeStatus() *NodeStatus {
	if x != nil {
		return x.NodeStatus
	}
	return nil
}

type NodeStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PostgreSQL connectivity
	PostgresqlConnected bool   `protobuf:"varint,1,opt,name=postgresql_connected,json=postgresqlConnected,proto3" json:"postgresql_connected,omitempty"`
	PostgresqlVersion   string `protobuf:"bytes,2,opt,name=postgresql_version,json=postgresqlVersion,proto3" json:"postgresql_version,omitempty"`
	// Resource metrics (optional)
	MemoryUsedBytes int64   `protobuf:"varint,3,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	CpuPercent      float32 `protobuf:"fixed32,4,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeStatus) Reset() {
	*x = NodeStatus{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeStatus) ProtoMessage() {}

func (x *NodeStatus) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeStatus.ProtoReflect.Descriptor instead.
func (*NodeStatus) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{9}
}

func (x *NodeStatus) GetPostgresqlConnected() bool {
	if x != nil {
		return x.PostgresqlConnected
	}
	return false
}

func (x *NodeStatus) GetPostgresqlVersion() string {
	if x != nil {
		return x.PostgresqlVersion
	}
	return ""
}

func (x *NodeStatus) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *NodeStatus) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

type HeartbeatResponse struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Acknowledged bool                   `protobuf:"varint,1,opt,name=acknowledged,proto3" json:"acknowledged,omitempty"`
	// Cluster updates since last heartbeat
	CoordinatorId string      `protobuf:"bytes,2,opt,name=coordinator_id,json=coordinatorId,proto3" json:"coordinator_id,omitempty"`
	UpdatedNodes  []*NodeInfo `protobuf:"bytes,3,rep,name=updated_nodes,json=updatedNodes,proto3" json:"updated_nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{10}
}

func (x *HeartbeatResponse) GetAcknowledged() bool {
	if x != nil {
		return x.Acknowledged
	}
	return false
}

func (x *HeartbeatResponse) GetCoordinatorId() string {
	if x != nil {
		return x.CoordinatorId
	}
	return ""
}

func (x *HeartbeatResponse) GetUpdatedNodes() []*NodeInfo {
	if x != nil {
		return x.UpdatedNodes
	}
	return nil
}

type SyncNodeMetadataRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The node sending its metadata
	Metadata      *NodeMetadata `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncNodeMetadataRequest) Reset() {
	*x = SyncNodeMetadataRequest{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNodeMetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNodeMetadataRequest) ProtoMessage() {}

func (x *SyncNodeMetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNodeMetadataRequest.ProtoReflect.Descriptor instead.
func (*SyncNodeMetadataRequest) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{11}
}

func (x *SyncNodeMetadataRequest) GetMetadata() *NodeMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SyncNodeMetadataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncNodeMetadataResponse) Reset() {
	*x = SyncNodeMetadataResponse{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncNodeMetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncNodeMetadataResponse) ProtoMessage() {}

func (x *SyncNodeMetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncNodeMetadataResponse.ProtoReflect.Descriptor instead.
func (*SyncNodeMetadataResponse) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{12}
}

func (x *SyncNodeMetadataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncNodeMetadataResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type NodeMetadata struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName        string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Status          string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                                         // healthy, degraded, unreachable, offline
	InitState       string                 `protobuf:"bytes,4,opt,name=init_state,json=initState,proto3" json:"init_state,omitempty"`                  // uninitialized, preparing, copying, catching_up, synchronized, diverged, failed, reinitializing
	InitSourceNode  string                 `protobuf:"bytes,5,opt,name=init_source_node,json=initSourceNode,proto3" json:"init_source_node,omitempty"` // node_id of the source used for initialization
	InitStartedAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=init_started_at,json=initStartedAt,proto3" json:"init_started_at,omitempty"`
	InitCompletedAt *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=init_completed_at,json=initCompletedAt,proto3" json:"init_completed_at,omitempty"`
	LastSeen        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"`
	GrpcHost        string                 `protobuf:"bytes,9,opt,name=grpc_host,json=grpcHost,proto3" json:"grpc_host,omitempty"`   // gRPC host for node-to-node communication
	GrpcPort        int32                  `protobuf:"varint,10,opt,name=grpc_port,json=grpcPort,proto3" json:"grpc_port,omitempty"` // gRPC port for node-to-node communication
	Priority        int32                  `protobuf:"varint,11,opt,name=priority,proto3" json:"priority,omitempty"`                 // Node priority (1-100, higher = preferred)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NodeMetadata) Reset() {
	*x = NodeMetadata{}
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeMetadata) ProtoMessage() {}

func (x *NodeMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_internal_repl_grpc_proto_repl_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeMetadata.ProtoReflect.Descriptor instead.
func (*NodeMetadata) Descriptor() ([]byte, []int) {
	return file_internal_repl_grpc_proto_repl_proto_rawDescGZIP(), []int{13}
}

func (x *NodeMetadata) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeMetadata) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeMetadata) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NodeMetadata) GetInitState() string {
	if x != nil {
		return x.InitState
	}
	return ""
}

func (x *NodeMetadata) GetInitSourceNode() string {
	if x != nil {
		return x.InitSourceNode
	}
	return ""
}

func (x *NodeMetadata) GetInitStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitStartedAt
	}
	return nil
}

func (x *NodeMetadata) GetInitCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InitCompletedAt
	}
	return nil
}

func (x *NodeMetadata) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *NodeMetadata) GetGrpcHost() string {
	if x != nil {
		return x.GrpcHost
	}
	return ""
}

func (x *NodeMetadata) GetGrpcPort() int32 {
	if x != nil {
		return x.GrpcPort
	}
	return 0
}

func (x *NodeMetadata) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

var File_internal_repl_grpc_proto_repl_proto protoreflect.FileDescriptor

const file_internal_repl_grpc_proto_repl_proto_rawDesc = "" +
	"\n" +
	"#internal/repl/grpc/proto/repl.proto\x12\rsteep.repl.v1\x1a\x1fgoogle/protobuf/timestamp.proto\".\n" +
	"\x12HealthCheckRequest\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\"\xdd\x03\n" +
	"\x13HealthCheckResponse\x12H\n" +
	"\x06status\x18\x01 \x01(\x0e20.steep.repl.v1.HealthCheckResponse.ServingStatusR\x06status\x12R\n" +
	"\n" +
	"components\x18\x02 \x03(\v22.steep.repl.v1.HealthCheckResponse.ComponentsEntryR\n" +
	"components\x12\x17\n" +
	"\anode_id\x18\x03 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x04 \x01(\tR\bnodeName\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12=\n" +
	"\fuptime_since\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vuptimeSince\x1a]\n" +
	"\x0fComponentsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.steep.repl.v1.ComponentHealthR\x05value:\x028\x01\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\"]\n" +
	"\x0fComponentHealth\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x8f\x01\n" +
	"\x13RegisterNodeRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\"\x9c\x01\n" +
	"\x14RegisterNodeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x12-\n" +
	"\x05nodes\x18\x03 \x03(\v2\x17.steep.repl.v1.NodeInfoR\x05nodes\x12%\n" +
	"\x0ecoordinator_id\x18\x04 \x01(\tR\rcoordinatorId\"6\n" +
	"\x0fGetNodesRequest\x12#\n" +
	"\rstatus_filter\x18\x01 \x03(\tR\fstatusFilter\"h\n" +
	"\x10GetNodesResponse\x12-\n" +
	"\x05nodes\x18\x01 \x03(\v2\x17.steep.repl.v1.NodeInfoR\x05nodes\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\"\xfc\x01\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04host\x18\x03 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x04 \x01(\x05R\x04port\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x12%\n" +
	"\x0eis_coordinator\x18\x06 \x01(\bR\risCoordinator\x127\n" +
	"\tlast_seen\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"g\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12:\n" +
	"\vnode_status\x18\x02 \x01(\v2\x19.steep.repl.v1.NodeStatusR\n" +
	"nodeStatus\"\xbb\x01\n" +
	"\n" +
	"NodeStatus\x121\n" +
	"\x14postgresql_connected\x18\x01 \x01(\bR\x13postgresqlConnected\x12-\n" +
	"\x12postgresql_version\x18\x02 \x01(\tR\x11postgresqlVersion\x12*\n" +
	"\x11memory_used_bytes\x18\x03 \x01(\x03R\x0fmemoryUsedBytes\x12\x1f\n" +
	"\vcpu_percent\x18\x04 \x01(\x02R\n" +
	"cpuPercent\"\x9c\x01\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\facknowledged\x18\x01 \x01(\bR\facknowledged\x12%\n" +
	"\x0ecoordinator_id\x18\x02 \x01(\tR\rcoordinatorId\x12<\n" +
	"\rupdated_nodes\x18\x03 \x03(\v2\x17.steep.repl.v1.NodeInfoR\fupdatedNodes\"R\n" +
	"\x17SyncNodeMetadataRequest\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.steep.repl.v1.NodeMetadataR\bmetadata\"J\n" +
	"\x18SyncNodeMetadataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc0\x03\n" +
	"\fNodeMetadata\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"init_state\x18\x04 \x01(\tR\tinitState\x12(\n" +
	"\x10init_source_node\x18\x05 \x01(\tR\x0einitSourceNode\x12B\n" +
	"\x0finit_started_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\rinitStartedAt\x12F\n" +
	"\x11init_completed_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0finitCompletedAt\x127\n" +
	"\tlast_seen\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x12\x1b\n" +
	"\tgrpc_host\x18\t \x01(\tR\bgrpcHost\x12\x1b\n" +
	"\tgrpc_port\x18\n" +
	" \x01(\x05R\bgrpcPort\x12\x1a\n" +
	"\bpriority\x18\v \x01(\x05R\bpriority2\xbe\x03\n" +
	"\vCoordinator\x12T\n" +
	"\vHealthCheck\x12!.steep.repl.v1.HealthCheckRequest\x1a\".steep.repl.v1.HealthCheckResponse\x12W\n" +
	"\fRegisterNode\x12\".steep.repl.v1.RegisterNodeRequest\x1a#.steep.repl.v1.RegisterNodeResponse\x12K\n" +
	"\bGetNodes\x12\x1e.steep.repl.v1.GetNodesRequest\x1a\x1f.steep.repl.v1.GetNodesResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.steep.repl.v1.HeartbeatRequest\x1a .steep.repl.v1.HeartbeatResponse\x12c\n" +
	"\x10SyncNodeMetadata\x12&.steep.repl.v1.SyncNodeMetadataRequest\x1a'.steep.repl.v1.SyncNodeMetadataResponseB Z\x1esteep/internal/repl/grpc/protob\x06proto3"

var (
	file_internal_repl_grpc_proto_repl_proto_rawDescOnce sync.Once
	file_internal_repl_grpc_proto_repl_proto_rawDescData []byte
)

func file_internal_repl_grpc_proto_repl_proto_rawDescGZIP() []byte {
	file_internal_repl_grpc_proto_repl_proto_rawDescOnce.Do(func() {
		file_internal_repl_grpc_proto_repl_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_repl_grpc_proto_repl_proto_rawDesc), len(file_internal_repl_grpc_proto_repl_proto_rawDesc)))
	})
	return file_internal_repl_grpc_proto_repl_proto_rawDescData
}

var file_internal_repl_grpc_proto_repl_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_repl_grpc_proto_repl_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_internal_repl_grpc_proto_repl_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: steep.repl.v1.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: steep.repl.v1.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: steep.repl.v1.HealthCheckResponse
	(*ComponentHealth)(nil),                // 3: steep.repl.v1.ComponentHealth
	(*RegisterNodeRequest)(nil),            // 4: steep.repl.v1.RegisterNodeRequest
	(*RegisterNodeResponse)(nil),           // 5: steep.repl.v1.RegisterNodeResponse
	(*GetNodesRequest)(nil),                // 6: steep.repl.v1.GetNodesRequest
	(*GetNodesResponse)(nil),               // 7: steep.repl.v1.GetNodesResponse
	(*NodeInfo)(nil),                       // 8: steep.repl.v1.NodeInfo
	(*HeartbeatRequest)(nil),               // 9: steep.repl.v1.HeartbeatRequest
	(*NodeStatus)(nil),                     // 10: steep.repl.v1.NodeStatus
	(*HeartbeatResponse)(nil),              // 11: steep.repl.v1.HeartbeatResponse
	(*SyncNodeMetadataRequest)(nil),        // 12: steep.repl.v1.SyncNodeMetadataRequest
	(*SyncNodeMetadataResponse)(nil),       // 13: steep.repl.v1.SyncNodeMetadataResponse
	(*NodeMetadata)(nil),                   // 14: steep.repl.v1.NodeMetadata
	nil,                                    // 15: steep.repl.v1.HealthCheckResponse.ComponentsEntry
	(*timestamppb.Timestamp)(nil),          // 16: google.protobuf.Timestamp
}
var file_internal_repl_grpc_proto_repl_proto_depIdxs = []int32{
	0,  // 0: steep.repl.v1.HealthCheckResponse.status:type_name -> steep.repl.v1.HealthCheckResponse.ServingStatus
	15, // 1: steep.repl.v1.HealthCheckResponse.components:type_name -> steep.repl.v1.HealthCheckResponse.ComponentsEntry
	16, // 2: steep.repl.v1.HealthCheckResponse.uptime_since:type_name -> google.protobuf.Timestamp
	8,  // 3: steep.repl.v1.RegisterNodeResponse.nodes:type_name -> steep.repl.v1.NodeInfo
	8,  // 4: steep.repl.v1.GetNodesResponse.nodes:type_name -> steep.repl.v1.NodeInfo
	16, // 5: steep.repl.v1.NodeInfo.last_seen:type_name -> google.protobuf.Timestamp
	10, // 6: steep.repl.v1.HeartbeatRequest.node_status:type_name -> steep.repl.v1.NodeStatus
	8,  // 7: steep.repl.v1.HeartbeatResponse.updated_nodes:type_name -> steep.repl.v1.NodeInfo
	14, // 8: steep.repl.v1.SyncNodeMetadataRequest.metadata:type_name -> steep.repl.v1.NodeMetadata
	16, // 9: steep.repl.v1.NodeMetadata.init_started_at:type_name -> google.protobuf.Timestamp
	16, // 10: steep.repl.v1.NodeMetadata.init_completed_at:type_name -> google.protobuf.Timestamp
	16, // 11: steep.repl.v1.NodeMetadata.last_seen:type_name -> google.protobuf.Timestamp
	3,  // 12: steep.repl.v1.HealthCheckResponse.ComponentsEntry.value:type_name -> steep.repl.v1.ComponentHealth
	1,  // 13: steep.repl.v1.Coordinator.HealthCheck:input_type -> steep.repl.v1.HealthCheckRequest
	4,  // 14: steep.repl.v1.Coordinator.RegisterNode:input_type -> steep.repl.v1.RegisterNodeRequest
	6,  // 15: steep.repl.v1.Coordinator.GetNodes:input_type -> steep.repl.v1.GetNodesRequest
	9,  // 16: steep.repl.v1.Coordinator.Heartbeat:input_type -> steep.repl.v1.HeartbeatRequest
	12, // 17: steep.repl.v1.Coordinator.SyncNodeMetadata:input_type -> steep.repl.v1.SyncNodeMetadataRequest
	2,  // 18: steep.repl.v1.Coordinator.HealthCheck:output_type -> steep.repl.v1.HealthCheckResponse
	5,  // 19: steep.repl.v1.Coordinator.RegisterNode:output_type -> steep.repl.v1.RegisterNodeResponse
	7,  // 20: steep.repl.v1.Coordinator.GetNodes:output_type -> steep.repl.v1.GetNodesResponse
	11, // 21: steep.repl.v1.Coordinator.Heartbeat:output_type -> steep.repl.v1.HeartbeatResponse
	13, // 22: steep.repl.v1.Coordinator.SyncNodeMetadata:output_type -> steep.repl.v1.SyncNodeMetadataResponse
	18, // [18:23] is the sub-list for method output_type
	13, // [13:18] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_internal_repl_grpc_proto_repl_proto_init() }
func file_internal_repl_grpc_proto_repl_proto_init() {
	if File_internal_repl_grpc_proto_repl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_repl_grpc_proto_repl_proto_rawDesc), len(file_internal_repl_grpc_proto_repl_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_repl_grpc_proto_repl_proto_goTypes,
		DependencyIndexes: file_internal_repl_grpc_proto_repl_proto_depIdxs,
		EnumInfos:         file_internal_repl_grpc_proto_repl_proto_enumTypes,
		MessageInfos:      file_internal_repl_grpc_proto_repl_proto_msgTypes,
	}.Build()
	File_internal_repl_grpc_proto_repl_proto = out.File
	file_internal_repl_grpc_proto_repl_proto_goTypes = nil
	file_internal_repl_grpc_proto_repl_proto_depIdxs = nil
}
